### ISSUE TITLE
Switching from GLEW to GLAD

### ISSUE THREAD

**Issue by DaanSander** [CoffeeLlamas/LlamaEngine#2]
GLEW includes every version of OpenGL, we could use GLAD and only select the versions we're gonna use as we're probably not gonna use anything above 3.4. I've already used glad in multiple projects and it seems to work fine.

The Window class will need to be reworked when using GLAD as it has a different way of initializing.

GLAD Web generator: [https://glad.dav1d.de/](url)

**Comment by Slinthn** [comment]
I think we can leave this for later since it's just optimisation. GLEW works just fine for now!
