### ISSUE TITLE
ShaderSource persistence

### ISSUE THREAD

**Issue by DaanSander** [CoffeeLlamas/LlamaEngine#4]
The shader source in `Shader.cpp` and `Shader.hpp` is never used after the shader creation is complete, this could probably be deleted afterwards to increase performance and general size of the shader. See: #3 Shader.hpp

**Comment by Slinthn** [comment]
Alright, I'll work on that and I suppose general optimization later!

**Comment by DaanSander** [comment]
Yeah, this is better, marking this as solved.
